from .user import User
from .journal import Journal
from .article import Article
from .review import Review
from .ai_analysis import AIAnalysis
from .submission import Submission
from .reviewer import Reviewer
from .notification import Notification
from .access_log import AccessLog
from .cv_request import CVRequest