"""add_cv_requests_table

Revision ID: ad39f7a638c9
Revises: b3414ab1386b
Create Date: 2026-04-16 23:38:16.540649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad39f7a638c9'
down_revision: Union[str, None] = 'b3414ab1386b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(), nullable=False),
    sa.Column('member_email', sa.String(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_email', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='cvrequeststatus'), nullable=False),
    sa.Column('approval_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_requests_approval_token'), 'cv_requests', ['approval_token'], unique=True)
    op.create_index(op.f('ix_cv_requests_id'), 'cv_requests', ['id'], unique=False)
    op.create_index(op.f('ix_cv_requests_requester_email'), 'cv_requests', ['requester_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_requests_requester_email'), table_name='cv_requests')
    op.drop_index(op.f('ix_cv_requests_id'), table_name='cv_requests')
    op.drop_index(op.f('ix_cv_requests_approval_token'), table_name='cv_requests')
    op.drop_table('cv_requests')
    # ### end Alembic commands ###
