"""initial schema

Revision ID: b3414ab1386b
Revises: 
Create Date: 2026-04-16 20:36:50.925402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3414ab1386b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    op.create_index(op.f('ix_journals_title'), 'journals', ['title'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='notification_channel'), nullable=False),
    sa.Column('trigger_event', sa.String(length=255), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_trigger_event'), 'notifications', ['trigger_event'], unique=False)
    op.create_table('reviewers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('expertise_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('max_assignments', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewers_email'), 'reviewers', ['email'], unique=True)
    op.create_index(op.f('ix_reviewers_is_active'), 'reviewers', ['is_active'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('paper_title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('redacted_pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('classified_field', sa.String(length=255), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending_classification', 'pending_assignment', 'under_review', 'revision_requested', 'accepted', 'rejected', name='submission_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_author_email'), 'submissions', ['author_email'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('link_token', sa.String(length=255), nullable=False),
    sa.Column('link_expires_at', sa.DateTime(), nullable=False),
    sa.Column('link_used', sa.Boolean(), nullable=False),
    sa.Column('score_originality', sa.Float(), nullable=True),
    sa.Column('score_technical', sa.Float(), nullable=True),
    sa.Column('score_relevance', sa.Float(), nullable=True),
    sa.Column('score_clarity', sa.Float(), nullable=True),
    sa.Column('score_references', sa.Float(), nullable=True),
    sa.Column('overall_recommendation', sa.Enum('accept', 'minor_revision', 'major_revision', 'reject', name='overall_recommendation'), nullable=True),
    sa.Column('comments_to_authors', sa.Text(), nullable=True),
    sa.Column('comments_to_editor', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'expired', name='review_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_link_token'), 'reviews', ['link_token'], unique=True)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_submission_id'), 'reviews', ['submission_id'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('link_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_link_token'), 'access_logs', ['link_token'], unique=False)
    op.create_index(op.f('ix_access_logs_review_id'), 'access_logs', ['review_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('plagiarism_score', sa.Integer(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_id'), 'ai_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analysis_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_access_logs_review_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_link_token'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_reviews_submission_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_link_token'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_author_email'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_reviewers_is_active'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_email'), table_name='reviewers')
    op.drop_table('reviewers')
    op.drop_index(op.f('ix_notifications_trigger_event'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_journals_title'), table_name='journals')
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###
