apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: jgair
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
